# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 716b0327f2efcc59855612cda1286d6f9bf2f436bbe34d655f2b9d1ed2d75ccd83e41fe7ed24edfad6bb9962503173fdc309559db54e1021cb6560840b209738

test:
  secret_key_base: 2ff2aa1328c19aae0a00bc634a3ceb0c9e6f078338873809c41edc775bbe27fab2cb279dd10cb9ca1b875bd746baccbfa79f6306b12e50e179670ea5cb0b3d5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
